<?php

/**
 * PluginaProductSlideshowSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaProductSlideshowSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaProductSlideshowSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaProductSlideshowSlot');
    }
}