<?php

/**
 * PluginaProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaProductCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaProductCategory');
    }
}