<?php

/**
 * PluginaProductItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaProductItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaProductItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaProductItem');
    }
}