<?php

/**
 * PluginProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginProduct extends BaseProduct
{
	public function getUrl() {
		return url_for('aProductItem_show', array('slug' => $this->slug, 'cat' => $this->ProductCategory->slug));
	}
	
	public function link_to() {
		return link_to($this, 'aProductItem_show', array('slug' => $this->slug, 'cat' => $this->ProductCategory->slug));
	}
	
	public function getPageSlug() {
		$perfix = sfConfig::get('app_samProduct_prefixProduct');
		return $perfix . $this->slug;
	}
	
	public function getText($limit = null) {
		$page = aPageTable::retrieveBySlug($this->getPageSlug());
		$text = '';
		
		foreach($page->getAllSlots() as $slot)
		{
			if(method_exists($slot, 'getText'))
			{
				$text .= $slot->getText();
			}
		}
		if(!is_null($limit))
		{
			$text = aString::limitWords($text, $limit);
		}
		
		return $text;
	}	
}