all:
  samProduct:
    prefixProduct: product- # slug prefix for every product area/slot
    prefixCategory: category- # slug prefix for every category area/slot
    max_per_page_category: 1
    max_per_page_product: 1