aProductItem_index:
  url:  /
  param: { module: aProductItem, action: index }
  class: aRoute
  
aProductItem_show:
  url:  /:slug
  param: { module: aProductItem, action: show }
  class: aRoute
  
aProductItem_category_add:
  url:  /admin/product_category_add
  param: { module: aProductItem, action: addProductCategory }
  class: aRoute

aProductItem_product_add:
  url:  /admin/product_add
  param: { module: aProductItem, action: addProduct }
  class: aRoute