aProductItem_index:
  url:  /
  param: { module: aProductItem, action: index }
  class: aRoute
  
aProductItem_categories:
 url:  /categories
 param: { module: aProductItem, action: categories }
 class: aRoute
 
aProductItem_delete:
  url: /delete/:type # category or product
  param: { module: aProductItem, action: delete }
  sf_method: [ DELETE ]
  class: aRoute
 
aProductItem_show:
  url:  /:slug
  param: { module: aProductItem, action: show }
  options: { model: Product, type: object }
  class: aDoctrineRoute
  
aProductItem_category_add:
  url:  /admin/product_category_add
  param: { module: aProductItem, action: addProductCategory }
  class: aRoute

aProductItem_product_add:
  url:  /admin/product_add
  param: { module: aProductItem, action: addProduct }
  class: aRoute