options:
  type: INNODB

aProductItem:
  actAs:
    Timestampable: ~
    Taggable: ~
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    page_id:
      type: integer
    title:
      type: string(255)
      notnull: true
    slug:
      type: varchar(255)
      notnull: true
    slug_saved:
      type: boolean
      default: false
    status:
      type: enum
      values: [draft, pending review, published ]
      notnull: true
      default: draft
    template:
      type: string(255)
      default: singleColumnTemplate
    published_at:
      type: timestamp
  relations:
    Page:
      class: aPage
      local: page_id
      foreign: id
      onDelete: CASCADE
      foreignAlias: BlogItem
      foreignType: one
    Categories:
      foreignAlias: ProductItems
      class: aProductCategory
      refClass: aProductItemToProductCategory
      local: product_item_id
      foreign: product_category_id
      
      
aProductItemToProductCategory:
  columns:
    product_item_id:
      type: integer
      primary: true
    product_category_id:
      type: integer
      primary: true
  relations:
    ProductItem:
      foreignAlias: ProductItemCategories
      class: aProductItem
      local: product_item_id
      onDelete: CASCADE
    ProductCategory:
      foreignAlias: ProductItemCategories
      class: aProductCategory
      local: product_category_id
      onDelete: CASCADE


aProductCategory:
  columns:
    title:
      type: string(255)
      notnull: true