# Your additional tables live here
Product:
  actAs:
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: false      
    I18n:
      fields: [title]
  columns:
    title: string(255)
    product_category_id: integer
  relations:
    ProductCategory: ~

ProductCategory:
  actAs:
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: false
    I18n:
      fields: [title]
  columns:
    title: string(255)
    product_category_id: integer
  relations:
    ParentProductCategory:
      local: product_category_id
      foreign: id
      class: ProductCategory
      foreignAlias: ChildProductCategory
aProductSlideshowSlot:
  # Doctrine doesn't produce useful forms with column aggregation inheritance anyway,
  # and slots often use serialization into the value column... the Doctrine forms are not
  # of much use here and they clutter the project
  options:
    symfony:
      form:   false
      filter: false

  # columns:
  #
  # You can add columns here. However, if you do not need foreign key relationships it is
  # often easier to store your data in the 'value' column via serialize(). If you do add columns, 
  # their names must be unique across all slots in your project, so use a unique prefix 
  # for your company.
    
  # This is how we are able to retrieve slots of various types with a single query from
  # a single table
  inheritance:
    extends: aSlot
    type: column_aggregation
    keyField: type
    keyValue: 'aProductSlideshow'
