# Your additional tables live here
Product:
  actAs:
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: false      
    I18n:
      fields: [title]
  columns:
    title: string(255)
    product_category_id: integer
  relations:
    ProductCategory: ~

ProductCategory:
  actAs:
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: false
    I18n:
      fields: [title]
  columns:
    title: string(255)
    product_category_id: integer
  relations:
    ParentProductCategory:
      local: product_category_id
      foreign: id
      class: ProductCategory
      foreignAlias: ChildProductCategory