# Your additional tables live here
Product:
  actAs:
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: true      
  columns:
    title: string(255)
    product_category_id: integer
  relations:
    ProductCategory: ~

ProductCategory:
  actAs:
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: true
  columns:
    title: string(255)
    product_category_id: integer
  relations:
    ProductCategory: ~